 # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'functions'
    - 'deploy'
    - 'hyungmin-testing-0927'
    - '--source'
    - 'gs://test-hyungmin1/testing-functions.zip'
    - '--region'
    - 'asia-northeast1'
