steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hyungmin-testing-0927-1
  - --region=asia-northeast1
  - --source=gs://test-hyungmin1/testing-functions.zip
  - --trigger-http
  - --runtime=nodejs20
  - --gen2
