steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - hyungmin-testing-0927-3
  - --region=asia-northeast1
  - --source=.
  - --runtime=nodejs20
  - --gen2
  - --trigger-http
